/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEscrow8183, IEscrow8183Interface } from "../../PolicyWallet.sol/IEscrow8183.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "provider",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "jobRef",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "evaluator",
        "type": "address"
      }
    ],
    "name": "fund",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IEscrow8183__factory {
    static readonly abi = _abi;
    static createInterface(): IEscrow8183Interface {
      return new Interface(_abi) as IEscrow8183Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEscrow8183 {
      return new Contract(address, _abi, runner) as unknown as IEscrow8183;
    }
  }
  