/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AgentRegistry8004Interface extends Interface {
    getFunction(nameOrSignature: "byIdentifier" | "idHashByAgentId" | "nextAgentId" | "register" | "setValidation" | "validationScore" | "validator"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentRegistered" | "ValidationRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'byIdentifier', values: [string]): string;
encodeFunctionData(functionFragment: 'idHashByAgentId', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextAgentId', values?: undefined): string;
encodeFunctionData(functionFragment: 'register', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'setValidation', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'validationScore', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'validator', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'byIdentifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'idHashByAgentId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextAgentId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'register', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setValidation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validationScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validator', data: BytesLike): Result;
  }

  
    export namespace AgentRegisteredEvent {
      export type InputTuple = [agentId: BigNumberish, owner: AddressLike, identifier: string];
      export type OutputTuple = [agentId: bigint, owner: string, identifier: string];
      export interface OutputObject {agentId: bigint, owner: string, identifier: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidationRecordedEvent {
      export type InputTuple = [agentId: BigNumberish, validator: AddressLike, score: BigNumberish];
      export type OutputTuple = [agentId: bigint, validator: string, score: bigint];
      export interface OutputObject {agentId: bigint, validator: string, score: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentRegistry8004 extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentRegistry8004;
    waitForDeployment(): Promise<this>;

    interface: AgentRegistry8004Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    byIdentifier: TypedContractMethod<
      [identifier: string, ],
      [[boolean, bigint, string, string, string, bigint] & {registered: boolean, agentId: bigint, owner: string, domain: string, cardUrl: string, score: bigint }],
      'view'
    >
    

    
    idHashByAgentId: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    nextAgentId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    register: TypedContractMethod<
      [identifier: string, domain: string, cardUrl: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    setValidation: TypedContractMethod<
      [agentId: BigNumberish, score: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    validationScore: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    validator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'byIdentifier'): TypedContractMethod<
      [identifier: string, ],
      [[boolean, bigint, string, string, string, bigint] & {registered: boolean, agentId: bigint, owner: string, domain: string, cardUrl: string, score: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'idHashByAgentId'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nextAgentId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'register'): TypedContractMethod<
      [identifier: string, domain: string, cardUrl: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setValidation'): TypedContractMethod<
      [agentId: BigNumberish, score: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'validationScore'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'validator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AgentRegistered'): TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
getEvent(key: 'ValidationRecorded'): TypedContractEvent<ValidationRecordedEvent.InputTuple, ValidationRecordedEvent.OutputTuple, ValidationRecordedEvent.OutputObject>;

    filters: {
      
      'AgentRegistered(uint256,address,string)': TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
      AgentRegistered: TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
    

      'ValidationRecorded(uint256,address,uint8)': TypedContractEvent<ValidationRecordedEvent.InputTuple, ValidationRecordedEvent.OutputTuple, ValidationRecordedEvent.OutputObject>;
      ValidationRecorded: TypedContractEvent<ValidationRecordedEvent.InputTuple, ValidationRecordedEvent.OutputTuple, ValidationRecordedEvent.OutputObject>;
    
    };
  }