/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IEscrow8183', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEscrow8183__factory>
getContractFactory(name: 'PolicyWallet', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PolicyWallet__factory>
getContractFactory(name: 'SimUSDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimUSDC__factory>
getContractFactory(name: 'AgentRegistry8004', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AgentRegistry8004__factory>
getContractFactory(name: 'Escrow8183', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Escrow8183__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>

  getContractAt(name: 'IEscrow8183', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEscrow8183>
getContractAt(name: 'PolicyWallet', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PolicyWallet>
getContractAt(name: 'SimUSDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimUSDC>
getContractAt(name: 'AgentRegistry8004', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AgentRegistry8004>
getContractAt(name: 'Escrow8183', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Escrow8183>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>

  deployContract(name: 'IEscrow8183', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEscrow8183>
deployContract(name: 'PolicyWallet', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PolicyWallet>
deployContract(name: 'SimUSDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimUSDC>
deployContract(name: 'AgentRegistry8004', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentRegistry8004>
deployContract(name: 'Escrow8183', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Escrow8183>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>

  deployContract(name: 'IEscrow8183', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEscrow8183>
deployContract(name: 'PolicyWallet', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PolicyWallet>
deployContract(name: 'SimUSDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimUSDC>
deployContract(name: 'AgentRegistry8004', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentRegistry8004>
deployContract(name: 'Escrow8183', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Escrow8183>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  