/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace StakedValidator {
      
    export type JobStruct = {requester: AddressLike, a: BigNumberish, b: BigNumberish, claimed: BigNumberish, commitEnd: BigNumberish, revealEnd: BigNumberish, challengeEnd: BigNumberish, committee: [AddressLike, AddressLike, AddressLike], finalized: boolean, accepted: boolean}

    export type JobStructOutput = [requester: string, a: bigint, b: bigint, claimed: bigint, commitEnd: bigint, revealEnd: bigint, challengeEnd: bigint, committee: [string, string, string], finalized: boolean, accepted: boolean] & {requester: string, a: bigint, b: bigint, claimed: bigint, commitEnd: bigint, revealEnd: bigint, challengeEnd: bigint, committee: [string, string, string], finalized: boolean, accepted: boolean }
  
    }

  export interface StakedValidatorInterface extends Interface {
    getFunction(nameOrSignature: "BOND" | "CHALLENGE_BLOCKS" | "COMMIT_BLOCKS" | "FEE" | "NO_SHOW_PENALTY" | "REVEAL_BLOCKS" | "REWARD" | "bounties" | "commit" | "commitmentFor" | "credit" | "deposit" | "finalize" | "getJob" | "locked" | "nextJobId" | "openJob" | "operators" | "proveFraud" | "registered" | "reserve" | "reveal" | "rewards" | "slashed" | "stake" | "submissions" | "withdrawCredit" | "withdrawStake"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Committed" | "Deposited" | "Finalized" | "FraudProven" | "JobOpened" | "Revealed" | "ValidatorSettled"): EventFragment;

    encodeFunctionData(functionFragment: 'BOND', values?: undefined): string;
encodeFunctionData(functionFragment: 'CHALLENGE_BLOCKS', values?: undefined): string;
encodeFunctionData(functionFragment: 'COMMIT_BLOCKS', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'NO_SHOW_PENALTY', values?: undefined): string;
encodeFunctionData(functionFragment: 'REVEAL_BLOCKS', values?: undefined): string;
encodeFunctionData(functionFragment: 'REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'bounties', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'commit', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'commitmentFor', values: [BigNumberish, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'credit', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalize', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getJob', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'locked', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nextJobId', values?: undefined): string;
encodeFunctionData(functionFragment: 'openJob', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'operators', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'proveFraud', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'registered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'reserve', values?: undefined): string;
encodeFunctionData(functionFragment: 'reveal', values: [BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'rewards', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'slashed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'stake', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'submissions', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawCredit', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawStake', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'BOND', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CHALLENGE_BLOCKS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'COMMIT_BLOCKS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'NO_SHOW_PENALTY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'REVEAL_BLOCKS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bounties', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitmentFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'credit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'locked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextJobId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operators', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proveFraud', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reveal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slashed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submissions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawCredit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawStake', data: BytesLike): Result;
  }

  
    export namespace CommittedEvent {
      export type InputTuple = [jobId: BigNumberish, validator: AddressLike, commitment: BytesLike];
      export type OutputTuple = [jobId: bigint, validator: string, commitment: string];
      export interface OutputObject {jobId: bigint, validator: string, commitment: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedEvent {
      export type InputTuple = [validator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [validator: string, amount: bigint];
      export interface OutputObject {validator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FinalizedEvent {
      export type InputTuple = [jobId: BigNumberish, accepted: boolean, correctAnswer: BigNumberish];
      export type OutputTuple = [jobId: bigint, accepted: boolean, correctAnswer: bigint];
      export interface OutputObject {jobId: bigint, accepted: boolean, correctAnswer: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FraudProvenEvent {
      export type InputTuple = [jobId: BigNumberish, validator: AddressLike, challenger: AddressLike];
      export type OutputTuple = [jobId: bigint, validator: string, challenger: string];
      export interface OutputObject {jobId: bigint, validator: string, challenger: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobOpenedEvent {
      export type InputTuple = [jobId: BigNumberish, requester: AddressLike, committee: [AddressLike, AddressLike, AddressLike]];
      export type OutputTuple = [jobId: bigint, requester: string, committee: [string, string, string]];
      export interface OutputObject {jobId: bigint, requester: string, committee: [string, string, string] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RevealedEvent {
      export type InputTuple = [jobId: BigNumberish, validator: AddressLike, answer: BigNumberish];
      export type OutputTuple = [jobId: bigint, validator: string, answer: bigint];
      export interface OutputObject {jobId: bigint, validator: string, answer: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidatorSettledEvent {
      export type InputTuple = [jobId: BigNumberish, validator: AddressLike, reward: BigNumberish, penalty: BigNumberish];
      export type OutputTuple = [jobId: bigint, validator: string, reward: bigint, penalty: bigint];
      export interface OutputObject {jobId: bigint, validator: string, reward: bigint, penalty: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StakedValidator extends BaseContract {
    
    connect(runner?: ContractRunner | null): StakedValidator;
    waitForDeployment(): Promise<this>;

    interface: StakedValidatorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BOND: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    CHALLENGE_BLOCKS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    COMMIT_BLOCKS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    NO_SHOW_PENALTY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    REVEAL_BLOCKS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    bounties: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    commit: TypedContractMethod<
      [id: BigNumberish, commitment: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    commitmentFor: TypedContractMethod<
      [id: BigNumberish, validator: AddressLike, answer: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    credit: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    finalize: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getJob: TypedContractMethod<
      [id: BigNumberish, ],
      [StakedValidator.JobStructOutput],
      'view'
    >
    

    
    locked: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    nextJobId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    openJob: TypedContractMethod<
      [a: BigNumberish, b: BigNumberish, claimed: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    operators: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    proveFraud: TypedContractMethod<
      [id: BigNumberish, validator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registered: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    reserve: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    reveal: TypedContractMethod<
      [id: BigNumberish, answer: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    rewards: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    slashed: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    stake: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    submissions: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[string, bigint, boolean, string] & {commitment: string, answer: bigint, revealed: boolean, challenger: string }],
      'view'
    >
    

    
    withdrawCredit: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawStake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BOND'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'CHALLENGE_BLOCKS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'COMMIT_BLOCKS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'NO_SHOW_PENALTY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'REVEAL_BLOCKS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bounties'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'commit'): TypedContractMethod<
      [id: BigNumberish, commitment: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'commitmentFor'): TypedContractMethod<
      [id: BigNumberish, validator: AddressLike, answer: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'credit'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'finalize'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getJob'): TypedContractMethod<
      [id: BigNumberish, ],
      [StakedValidator.JobStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'locked'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextJobId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'openJob'): TypedContractMethod<
      [a: BigNumberish, b: BigNumberish, claimed: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'operators'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proveFraud'): TypedContractMethod<
      [id: BigNumberish, validator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registered'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'reserve'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'reveal'): TypedContractMethod<
      [id: BigNumberish, answer: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewards'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'slashed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submissions'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[string, bigint, boolean, string] & {commitment: string, answer: bigint, revealed: boolean, challenger: string }],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawCredit'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawStake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Committed'): TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'Finalized'): TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
getEvent(key: 'FraudProven'): TypedContractEvent<FraudProvenEvent.InputTuple, FraudProvenEvent.OutputTuple, FraudProvenEvent.OutputObject>;
getEvent(key: 'JobOpened'): TypedContractEvent<JobOpenedEvent.InputTuple, JobOpenedEvent.OutputTuple, JobOpenedEvent.OutputObject>;
getEvent(key: 'Revealed'): TypedContractEvent<RevealedEvent.InputTuple, RevealedEvent.OutputTuple, RevealedEvent.OutputObject>;
getEvent(key: 'ValidatorSettled'): TypedContractEvent<ValidatorSettledEvent.InputTuple, ValidatorSettledEvent.OutputTuple, ValidatorSettledEvent.OutputObject>;

    filters: {
      
      'Committed(uint256,address,bytes32)': TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
      Committed: TypedContractEvent<CommittedEvent.InputTuple, CommittedEvent.OutputTuple, CommittedEvent.OutputObject>;
    

      'Deposited(address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'Finalized(uint256,bool,int128)': TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
      Finalized: TypedContractEvent<FinalizedEvent.InputTuple, FinalizedEvent.OutputTuple, FinalizedEvent.OutputObject>;
    

      'FraudProven(uint256,address,address)': TypedContractEvent<FraudProvenEvent.InputTuple, FraudProvenEvent.OutputTuple, FraudProvenEvent.OutputObject>;
      FraudProven: TypedContractEvent<FraudProvenEvent.InputTuple, FraudProvenEvent.OutputTuple, FraudProvenEvent.OutputObject>;
    

      'JobOpened(uint256,address,address[3])': TypedContractEvent<JobOpenedEvent.InputTuple, JobOpenedEvent.OutputTuple, JobOpenedEvent.OutputObject>;
      JobOpened: TypedContractEvent<JobOpenedEvent.InputTuple, JobOpenedEvent.OutputTuple, JobOpenedEvent.OutputObject>;
    

      'Revealed(uint256,address,int128)': TypedContractEvent<RevealedEvent.InputTuple, RevealedEvent.OutputTuple, RevealedEvent.OutputObject>;
      Revealed: TypedContractEvent<RevealedEvent.InputTuple, RevealedEvent.OutputTuple, RevealedEvent.OutputObject>;
    

      'ValidatorSettled(uint256,address,uint256,uint256)': TypedContractEvent<ValidatorSettledEvent.InputTuple, ValidatorSettledEvent.OutputTuple, ValidatorSettledEvent.OutputObject>;
      ValidatorSettled: TypedContractEvent<ValidatorSettledEvent.InputTuple, ValidatorSettledEvent.OutputTuple, ValidatorSettledEvent.OutputObject>;
    
    };
  }