/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ValidatorQuorum {
      
    export type RoundStruct = {id: BigNumberish, expiresAt: BigNumberish, approvals: BigNumberish, responses: BigNumberish, score: BigNumberish}

    export type RoundStructOutput = [id: bigint, expiresAt: bigint, approvals: bigint, responses: bigint, score: bigint] & {id: bigint, expiresAt: bigint, approvals: bigint, responses: bigint, score: bigint }
  
    }

  export interface ValidatorQuorumInterface extends Interface {
    getFunction(nameOrSignature: "beginRound" | "controller" | "isMember" | "members" | "registry" | "rounds" | "status" | "submit" | "votes"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RoundOpened" | "VoteRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'beginRound', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'controller', values?: undefined): string;
encodeFunctionData(functionFragment: 'isMember', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'members', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'rounds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'status', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submit', values: [BigNumberish, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'votes', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'beginRound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'controller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isMember', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'members', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rounds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'status', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votes', data: BytesLike): Result;
  }

  
    export namespace RoundOpenedEvent {
      export type InputTuple = [agentId: BigNumberish, roundId: BigNumberish, expiresAt: BigNumberish];
      export type OutputTuple = [agentId: bigint, roundId: bigint, expiresAt: bigint];
      export interface OutputObject {agentId: bigint, roundId: bigint, expiresAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteRecordedEvent {
      export type InputTuple = [agentId: BigNumberish, roundId: BigNumberish, validator: AddressLike, score: BigNumberish, reportHash: BytesLike];
      export type OutputTuple = [agentId: bigint, roundId: bigint, validator: string, score: bigint, reportHash: string];
      export interface OutputObject {agentId: bigint, roundId: bigint, validator: string, score: bigint, reportHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ValidatorQuorum extends BaseContract {
    
    connect(runner?: ContractRunner | null): ValidatorQuorum;
    waitForDeployment(): Promise<this>;

    interface: ValidatorQuorumInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    beginRound: TypedContractMethod<
      [agentId: BigNumberish, validFor: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    controller: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isMember: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    members: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rounds: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {id: bigint, expiresAt: bigint, approvals: bigint, responses: bigint, score: bigint }],
      'view'
    >
    

    
    status: TypedContractMethod<
      [agentId: BigNumberish, ],
      [[ValidatorQuorum.RoundStructOutput, boolean, bigint] & {round: ValidatorQuorum.RoundStructOutput, eligible: boolean, score: bigint }],
      'view'
    >
    

    
    submit: TypedContractMethod<
      [agentId: BigNumberish, roundId: BigNumberish, score: BigNumberish, reportHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    votes: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[bigint, bigint, string] & {roundId: bigint, score: bigint, reportHash: string }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'beginRound'): TypedContractMethod<
      [agentId: BigNumberish, validFor: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'controller'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isMember'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'members'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rounds'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {id: bigint, expiresAt: bigint, approvals: bigint, responses: bigint, score: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'status'): TypedContractMethod<
      [agentId: BigNumberish, ],
      [[ValidatorQuorum.RoundStructOutput, boolean, bigint] & {round: ValidatorQuorum.RoundStructOutput, eligible: boolean, score: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'submit'): TypedContractMethod<
      [agentId: BigNumberish, roundId: BigNumberish, score: BigNumberish, reportHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'votes'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[bigint, bigint, string] & {roundId: bigint, score: bigint, reportHash: string }],
      'view'
    >;

    getEvent(key: 'RoundOpened'): TypedContractEvent<RoundOpenedEvent.InputTuple, RoundOpenedEvent.OutputTuple, RoundOpenedEvent.OutputObject>;
getEvent(key: 'VoteRecorded'): TypedContractEvent<VoteRecordedEvent.InputTuple, VoteRecordedEvent.OutputTuple, VoteRecordedEvent.OutputObject>;

    filters: {
      
      'RoundOpened(uint256,uint256,uint256)': TypedContractEvent<RoundOpenedEvent.InputTuple, RoundOpenedEvent.OutputTuple, RoundOpenedEvent.OutputObject>;
      RoundOpened: TypedContractEvent<RoundOpenedEvent.InputTuple, RoundOpenedEvent.OutputTuple, RoundOpenedEvent.OutputObject>;
    

      'VoteRecorded(uint256,uint256,address,uint8,bytes32)': TypedContractEvent<VoteRecordedEvent.InputTuple, VoteRecordedEvent.OutputTuple, VoteRecordedEvent.OutputObject>;
      VoteRecorded: TypedContractEvent<VoteRecordedEvent.InputTuple, VoteRecordedEvent.OutputTuple, VoteRecordedEvent.OutputObject>;
    
    };
  }