/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PolicyWalletInterface extends Interface {
    getFunction(nameOrSignature: "consume" | "cumulativeCap" | "fundEscrow" | "owner" | "pay" | "perTxCap" | "receipts" | "setCaps" | "spent" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CapsUpdated" | "EscrowFunded" | "PaymentSettled" | "ReceiptConsumed"): EventFragment;

    encodeFunctionData(functionFragment: 'consume', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'cumulativeCap', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundEscrow', values: [AddressLike, AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pay', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'perTxCap', values?: undefined): string;
encodeFunctionData(functionFragment: 'receipts', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setCaps', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'spent', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'consume', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cumulativeCap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'perTxCap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receipts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCaps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'spent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace CapsUpdatedEvent {
      export type InputTuple = [perTxCap: BigNumberish, cumulativeCap: BigNumberish];
      export type OutputTuple = [perTxCap: bigint, cumulativeCap: bigint];
      export interface OutputObject {perTxCap: bigint, cumulativeCap: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowFundedEvent {
      export type InputTuple = [jobId: BigNumberish, escrow: AddressLike, provider: AddressLike, amount: BigNumberish];
      export type OutputTuple = [jobId: bigint, escrow: string, provider: string, amount: bigint];
      export interface OutputObject {jobId: bigint, escrow: string, provider: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentSettledEvent {
      export type InputTuple = [receiptId: BytesLike, to: AddressLike, amount: BigNumberish, memo: string];
      export type OutputTuple = [receiptId: string, to: string, amount: bigint, memo: string];
      export interface OutputObject {receiptId: string, to: string, amount: bigint, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReceiptConsumedEvent {
      export type InputTuple = [receiptId: BytesLike, by: AddressLike];
      export type OutputTuple = [receiptId: string, by: string];
      export interface OutputObject {receiptId: string, by: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PolicyWallet extends BaseContract {
    
    connect(runner?: ContractRunner | null): PolicyWallet;
    waitForDeployment(): Promise<this>;

    interface: PolicyWalletInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    consume: TypedContractMethod<
      [receiptId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    cumulativeCap: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fundEscrow: TypedContractMethod<
      [escrow: AddressLike, provider: AddressLike, amount: BigNumberish, jobRef: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pay: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, memo: string, ],
      [string],
      'nonpayable'
    >
    

    
    perTxCap: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    receipts: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, boolean] & {payer: string, to: string, amount: bigint, consumed: boolean }],
      'view'
    >
    

    
    setCaps: TypedContractMethod<
      [_perTxCap: BigNumberish, _cumulativeCap: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    spent: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'consume'): TypedContractMethod<
      [receiptId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cumulativeCap'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fundEscrow'): TypedContractMethod<
      [escrow: AddressLike, provider: AddressLike, amount: BigNumberish, jobRef: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pay'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, memo: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'perTxCap'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'receipts'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, boolean] & {payer: string, to: string, amount: bigint, consumed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'setCaps'): TypedContractMethod<
      [_perTxCap: BigNumberish, _cumulativeCap: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'spent'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'CapsUpdated'): TypedContractEvent<CapsUpdatedEvent.InputTuple, CapsUpdatedEvent.OutputTuple, CapsUpdatedEvent.OutputObject>;
getEvent(key: 'EscrowFunded'): TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
getEvent(key: 'PaymentSettled'): TypedContractEvent<PaymentSettledEvent.InputTuple, PaymentSettledEvent.OutputTuple, PaymentSettledEvent.OutputObject>;
getEvent(key: 'ReceiptConsumed'): TypedContractEvent<ReceiptConsumedEvent.InputTuple, ReceiptConsumedEvent.OutputTuple, ReceiptConsumedEvent.OutputObject>;

    filters: {
      
      'CapsUpdated(uint256,uint256)': TypedContractEvent<CapsUpdatedEvent.InputTuple, CapsUpdatedEvent.OutputTuple, CapsUpdatedEvent.OutputObject>;
      CapsUpdated: TypedContractEvent<CapsUpdatedEvent.InputTuple, CapsUpdatedEvent.OutputTuple, CapsUpdatedEvent.OutputObject>;
    

      'EscrowFunded(uint256,address,address,uint256)': TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
      EscrowFunded: TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
    

      'PaymentSettled(bytes32,address,uint256,string)': TypedContractEvent<PaymentSettledEvent.InputTuple, PaymentSettledEvent.OutputTuple, PaymentSettledEvent.OutputObject>;
      PaymentSettled: TypedContractEvent<PaymentSettledEvent.InputTuple, PaymentSettledEvent.OutputTuple, PaymentSettledEvent.OutputObject>;
    

      'ReceiptConsumed(bytes32,address)': TypedContractEvent<ReceiptConsumedEvent.InputTuple, ReceiptConsumedEvent.OutputTuple, ReceiptConsumedEvent.OutputObject>;
      ReceiptConsumed: TypedContractEvent<ReceiptConsumedEvent.InputTuple, ReceiptConsumedEvent.OutputTuple, ReceiptConsumedEvent.OutputObject>;
    
    };
  }