/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface Escrow8183Interface extends Interface {
    getFunction(nameOrSignature: "attest" | "fund" | "jobs" | "nextJobId" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EscrowAttested" | "EscrowFunded"): EventFragment;

    encodeFunctionData(functionFragment: 'attest', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'fund', values: [AddressLike, BigNumberish, string, AddressLike]): string;
encodeFunctionData(functionFragment: 'jobs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextJobId', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'attest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jobs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextJobId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace EscrowAttestedEvent {
      export type InputTuple = [jobId: BigNumberish, evaluator: AddressLike, pass: boolean];
      export type OutputTuple = [jobId: bigint, evaluator: string, pass: boolean];
      export interface OutputObject {jobId: bigint, evaluator: string, pass: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowFundedEvent {
      export type InputTuple = [jobId: BigNumberish, client: AddressLike, provider: AddressLike, amount: BigNumberish, jobRef: string];
      export type OutputTuple = [jobId: bigint, client: string, provider: string, amount: bigint, jobRef: string];
      export interface OutputObject {jobId: bigint, client: string, provider: string, amount: bigint, jobRef: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Escrow8183 extends BaseContract {
    
    connect(runner?: ContractRunner | null): Escrow8183;
    waitForDeployment(): Promise<this>;

    interface: Escrow8183Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attest: TypedContractMethod<
      [jobId: BigNumberish, pass: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    fund: TypedContractMethod<
      [provider: AddressLike, amount: BigNumberish, jobRef: string, evaluator: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    jobs: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, string, bigint] & {client: string, provider: string, evaluator: string, amount: bigint, jobRef: string, status: bigint }],
      'view'
    >
    

    
    nextJobId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attest'): TypedContractMethod<
      [jobId: BigNumberish, pass: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fund'): TypedContractMethod<
      [provider: AddressLike, amount: BigNumberish, jobRef: string, evaluator: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'jobs'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, string, bigint] & {client: string, provider: string, evaluator: string, amount: bigint, jobRef: string, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'nextJobId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'EscrowAttested'): TypedContractEvent<EscrowAttestedEvent.InputTuple, EscrowAttestedEvent.OutputTuple, EscrowAttestedEvent.OutputObject>;
getEvent(key: 'EscrowFunded'): TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;

    filters: {
      
      'EscrowAttested(uint256,address,bool)': TypedContractEvent<EscrowAttestedEvent.InputTuple, EscrowAttestedEvent.OutputTuple, EscrowAttestedEvent.OutputObject>;
      EscrowAttested: TypedContractEvent<EscrowAttestedEvent.InputTuple, EscrowAttestedEvent.OutputTuple, EscrowAttestedEvent.OutputObject>;
    

      'EscrowFunded(uint256,address,address,uint256,string)': TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
      EscrowFunded: TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
    
    };
  }